### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by yikiii** [Hydro3639/NanoPhase#3]
hi, something wrong with installation.

install via mamba：
mamba create -n nanophase python=3.8 -y
mamba activate nanophase
mamba install -c nanophase nanophase -y

but：

Could not solve for environment specs
Encountered problems while solving:
  - package nanophase-0.2.1-0 requires matplotlib 3.5.1 py38h578d9bd_0, but none of the providers can be installed

**Comment by yikiii** [comment]
I found type `conda config --set channel_priority flexible` first maybe work

**Comment by Hydro3639** [comment]
Good to know you fix this. I would suggest adding channels of `defaults `, `conda-forge`, and `bioconda` to avoid some similar errors. Please let me know if you need more help.

**Comment by yikiii** [comment]
Thanks for your reply.

something wrong with metawrap refinement:
```
from Bio import SeqIO
ImportError: No module named Bio
```
I'm sure the package is installed.
```
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Bio import SeqIO
>>> 
```
I modify the file _nanophase.meta_ to use my conda env metawrap-env installed before, it works. 

by the way, where is medaka_model' directory,
in case I want to download new model from https://github.com/nanoporetech/medaka/tree/master/medaka/data to use

**Comment by Hydro3639** [comment]
Yes, currently, the `medaka` was not the latest one. I will update `medaka` and other packages in the next release. Currently, I will suggest to uninstall `medaka` first in `nanophase` env, then install medaka (v1.7.2), which you can use all new models. Hope it helps.

**Comment by yikiii** [comment]
I'll try. Thanks for all your work!
